# Generated by Django 5.1 on 2024-09-11 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sub_images',
            field=models.TextField(blank=True, null=True),
        ),
    ]
